version: "3.9"
services:
  deploy:
    container_name: taskManagerApp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localPostgresSQLDB:5433/task_manager_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    networks:
      java13-network:
        aliases:
          - taskManagerApp
networks:
  java13-network:
    name: 'task_manager_network'

