version: "3.9"
services:
  postgres:
    container_name: localPostgresSQLDBforTaskManager
    image: postgres
    environment:
      POSTGRES_DB: "task_manager_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5433:5433"
